<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Karakter;

class KarakterSeeder extends Seeder
{
    public function run()
    {
        Karakter::truncate();

        Karakter::insert([
            [
                'kode' => '001',
                'nama' => 'Mario',
                'game' => 'Super Mario Bros',
                'jenis' => 'Plumber',
                'foto' => 'mario.jpg',
                'background' => 'mario-bg.jpg',
                'warna' => '#ff0000',
                'deskripsi' => 'Seorang tukang ledeng yang berpetualang di dunia Mushroom Kingdom.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '002',
                'nama' => 'Link(BOTW)',
                'game' => 'The Legend of Zelda',
                'jenis' => 'Hero of Hyrule',
                'foto' => 'link.jpg',
                'background' => 'zelda-bg.jpg',
                'warna' => '#00bfff',
                'deskripsi' => 'Pahlawan dari Hyrule yang bertarung melawan kejahatan Ganon.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '003',
                'nama' => 'Pikachu',
                'game' => 'Pokémon',
                'jenis' => 'Electric Pokémon',
                'foto' => 'pikachu.jpg',
                'background' => 'pikachu-bg.jpg',
                'warna' => '#FFD700',
                'deskripsi' => 'Pokémon listrik yang setia dan ceria, mampu mengeluarkan serangan petir dari pipinya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '004',
                'nama' => 'Lara Croft',
                'game' => 'Tomb Raider',
                'jenis' => 'Arkeolog',
                'foto' => 'lara.jpg',
                'background' => 'tomb-bg.jpg',
                'warna' => '#b8860b',
                'deskripsi' => 'Arkeolog petualang yang menjelajahi reruntuhan kuno di seluruh dunia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '005',
                'nama' => 'Phainon',
                'game' => 'Honkai: Star Rail',
                'jenis' => 'Deliverer',
                'foto' => 'phainon.jpg',
                'background' => 'phainon-bg.jpg',
                'warna' => '#ffd700',
                'deskripsi' => 'Pewaris cahaya dunia dari Amphoreus, sosok tenang namun tragis yang rela mengorbankan diri demi melindungi dunia dari kehancuran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '006',
                'nama' => 'Six',
                'game' => 'Little Nightmares',
                'jenis' => 'Survivor',
                'foto' => 'six.jpg',
                'background' => 'six-bg.jpg',
                'warna' => '#ffff66',
                'deskripsi' => 'Terjebak di kedalaman tergelap The Maw, kelaparan dan sendirian, dunia Six penuh bahaya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '007',
                'nama' => 'Isaac Clarke',
                'game' => 'Dead Space',
                'jenis' => 'Engineer',
                'foto' => 'isaac.jpg',
                'background' => 'isaac-bg.jpg',
                'warna' => '#00ffaa',
                'deskripsi' => 'Isaac Clarke adalah mantan insinyur sistem kapal yang memainkan peran penting dalam peristiwa seputar Marker.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '008',
                'nama' => 'Destined One',
                'game' => 'Black Myth: Wukong',
                'jenis' => 'Sage Warrior',
                'foto' => 'one.jpg',
                'background' => 'one-bg.jpg',
                'warna' => '#ff6600',
                'deskripsi' => 'Monyet dari Gunung Huaguo yang berusaha menghidupkan kembali Raja Kera legendaris Sun Wukong.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '009',
                'nama' => 'Ranni The Witch',
                'game' => 'Elden Ring',
                'jenis' => 'Lunar Princess',
                'foto' => 'ranni.jpg',
                'background' => 'ranni-bg.jpg',
                'warna' => '#66ccff',
                'deskripsi' => 'Penyihir misterius yang menolak takdir dan mencari kebebasan di bawah cahaya bulan biru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '010',
                'nama' => 'Olga Marie Animusphere',
                'game' => 'Fate/Grand Order',
                'jenis' => 'Chaldea Director',
                'foto' => 'olgamarie.jpg',
                'background' => 'summon-bg.jpg',
                'warna' => '#d46aff',
                'deskripsi' => 'Pemimpin yang tegas dan sombong namun berhati lembut.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '011',
                'nama' => 'Ghost',
                'game' => 'Call Of Duty',
                'jenis' => 'British SAS Operator',
                'foto' => 'ghost.jpg',
                'background' => 'cod-bg.jpg',
                'warna' => '#808080',
                'deskripsi' => 'Simon "Ghost" Riley adalah operator SAS Inggris dengan balaklava tengkorak ikonik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '012',
                'nama' => 'Solaire',
                'game' => 'Dark Souls',
                'jenis' => 'Knight of Astora',
                'foto' => 'solaire.jpg',
                'background' => 'ds1-bg.jpg',
                'warna' => '#FFD866',
                'deskripsi' => 'Seorang prajurit Undead yang mencari mataharinya sendiri.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '013',
                'nama' => 'Furina',
                'game' => 'Genshin Impact',
                'jenis' => 'Actress',
                'foto' => 'furina.jpg',
                'background' => 'fontaine-bg.jpg',
                'warna' => '#00E4FF',
                'deskripsi' => 'Wadah manusia yang memainkan peran Hydro Archon Fontaine selama 500 tahun.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '014',
                'nama' => 'The Hunter',
                'game' => 'Bloodborne',
                'jenis' => 'Beast Slayer',
                'foto' => 'thehunter.jpg',
                'background' => 'yharnam-bg.jpg',
                'warna' => '#B22222',
                'deskripsi' => 'Pemburu tanpa nama yang berjuang melawan mimpi buruk Yharnam.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode' => '015',
                'nama' => 'Destiny (Anna)',
                'game' => 'Takt Op. Symphony',
                'jenis' => 'Musicart',
                'foto' => 'destiny.jpg',
                'background' => 'taktop-bg.jpg',
                'warna' => '#ff3366',
                'deskripsi' => 'Musicart anggun dengan prinsip hidup yang tegas dan dingin.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}